# ceos3: Leaf1
ospf_router_id: "3.3.3.3"
ospf_networks:
  - prefix: "3.3.3.3/32"
    area: "0.0.0.0"
  - prefix: "10.1.0.0/30"
    area: "0.0.0.0"
  - prefix: "10.2.0.0/30"
    area: "0.0.0.0"
  - prefix: "10.3.0.0/30"
    area: "0.0.0.0"
