all:
  children:
    spine:
      hosts:
        spine1:
          ansible_host: clab-lab06-l3evpn-spine1
        spine2:
          ansible_host: clab-lab06-l3evpn-spine2
    leaf:
      hosts:
        leaf1:
          ansible_host: clab-lab06-l3evpn-leaf1
        leaf2:
          ansible_host: clab-lab06-l3evpn-leaf2
    host:
      hosts:
        host1:
          ansible_host: clab-lab06-l3evpn-host1
        host2:
          ansible_host: clab-lab06-l3evpn-host2
        host3:
          ansible_host: clab-lab06-l3evpn-host3
