# ceos1: Spine1
ospf_router_id: "1.1.1.1"
ospf_networks:
  - prefix: "1.1.1.1/32"
    area: "0.0.0.0"
  - prefix: "10.1.0.0/30"
    area: "0.0.0.0"
  - prefix: "10.1.0.4/30"
    area: "0.0.0.0"
  - prefix: "10.1.0.8/30"
    area: "0.0.0.0"
  - prefix: "10.1.0.12/30"
    area: "0.0.0.0"
