# ceos6: Leaf4
ospf_router_id: "6.6.6.6"
ospf_networks:
  - prefix: "6.6.6.6/32"
    area: "0.0.0.0"
  - prefix: "10.1.0.12/30"
    area: "0.0.0.0"
  - prefix: "10.2.0.12/30"
    area: "0.0.0.0"
  - prefix: "10.3.0.4/30"
    area: "0.0.0.0"
